### ISSUE TITLE
Limited to iOS

### ISSUE THREAD

**Issue by dmontay** [CaptainRedmuff/UIColor-Pantone#2]
Does the use of UIColor in the swift file limit it to iOS?

**Comment by zilmarinen** [comment]
There is a swift implementation but I believe this will only work on iOS. 

https://github.com/CaptainRedmuff/UIColor-Pantone/blob/master/Source/UIColor%2BPantone.swift

**Comment by dmontay** [comment]
i can confirm this is the case, a nice little project nonetheless.

**Comment by zilmarinen** [comment]
If you need a version that works with OS X, you can use NSColor+Pantone instead.

https://github.com/CaptainRedmuff/NSColor-Pantone

**Comment by dmontay** [comment]
Thanks Zack, I was using that before you released the swift version and can confirm it works :)
